create_target_positions:
  ros__parameters:
    center_x: 5.0
    center_y: 5.0
    start_angle: 0.0
    radius: 8.0

/**/control_system_proportional:
  ros__parameters:
    vel_gain: 1.0
    acc_gain: 0.7
    max_vel: 1.0
    max_acc: 0.5

/**/tracking_control:
  ros__parameters:
    k1: 1.1 # Velocity
    k2: 0.6 # Angular Twist

/**: # This will put all the parameters in every node
  ros__parameters:
    num_robots: 4 # Numbers of robots to be spawned
    dist_between_robots: 4 # Distance in meters between robots
    dist_l: 0.24 # Distance between p and p tilde
    publish_rate: 0.01 # Time intervals between publishes

