create_target_positions: 
  ros__parameters:
    center_x: 1.0
    center_y: 1.0
    start_angle: 0.0
    radius: 3.0

/**/control_system_proportional:
  ros__parameters:
    vel_gain: 0.2
    acc_gain: 0.5
    max_vel: 1.0
    max_acc: 1.0
    
/**: # This will put all the parameters in every node
  ros__parameters:
    num_robots: 1 # Numbers of robots to be spawned
    dist_between_robots: 1 # Distance in meters between robots    
    dist_l: 0.24 # Distance between p and p tilde
    publish_rate: 0.01 # Frequency at which the system publish
    #vel_gain: 0.1
    #acc_gain: 0.5
    #max_vel: 1.0
    #max_acc: 1.0

