create_target_positions: 
  ros__parameters:
    center_x: 10.0
    center_y: 10.0
    start_angle: 0.0
    radius: 5.0

control_system_proportional:
  ros__parameters:
    vel_gain: 0.1
    acc_gain: 1.0
    max_vel: 10.0
    max_acc: 10.0
    
/**: # This will put all the parameters in every node
  ros__parameters:
    num_robots: 1 # Numbers of robots to be spawned
    dist_between_robots: 1 # Distance in meters between robots    
    dist_l: 0.24 # Distance between p and p tilde
    publish_rate: 0.1 # Frequency at which the system publish

